@startuml

title __WITHADAPTER's Class Diagram__\n

  namespace theory.structural.adapter {
    class theory.structural.adapter.GermanConnector {
        + giveElectricityAsPerGermanRegulation()
    }
  }
  

  namespace theory.structural.adapter {
    interface theory.structural.adapter.GermanConnectorInterface {
        {abstract} + giveElectricityAsPerGermanRegulation()
    }
  }
  

  namespace theory.structural.adapter {
    class theory.structural.adapter.GermanToUkConnectorAdapter {
        + GermanToUkConnectorAdapter()
        + giveElectricityAsPerUkRegulation()
    }
  }
  

  namespace theory.structural.adapter {
    class theory.structural.adapter.Main {
        {static} + main()
    }
  }
  

  namespace theory.structural.adapter {
    class theory.structural.adapter.UkConnector {
        + giveElectricityAsPerUkRegulation()
    }
  }
  

  namespace theory.structural.adapter {
    interface theory.structural.adapter.UkConnectorInterface {
        {abstract} + giveElectricityAsPerUkRegulation()
    }
  }
  

  theory.structural.adapter.GermanConnector .up.|> theory.structural.adapter.GermanConnectorInterface
  theory.structural.adapter.GermanToUkConnectorAdapter .up.|> theory.structural.adapter.UkConnectorInterface
  theory.structural.adapter.GermanToUkConnectorAdapter o-- theory.structural.adapter.GermanConnectorInterface : germanConnector
  theory.structural.adapter.UkConnector .up.|> theory.structural.adapter.UkConnectorInterface


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
