create table SALES_DYC_WW_MEAN_TOP_10(
DRUG_ID VARCHAR2(10),
YEAR    VARCHAR2(10),
COMPANY_ID  VARCHAR2(10),
COMPANY_NAME    VARCHAR2(500),
MEAN    NUMBER);
create table SALES_DYR_REGIONAL_MEAN(
DRUG_ID VARCHAR2(10),
YEAR    VARCHAR2(10),
REGION_ID   VARCHAR2(10),
MEAN    NUMBER);
create table SALES_DY_WW_MEAN(
DRUG_ID VARCHAR2(10),
YEAR    VARCHAR2(10),
MEAN    NUMBER,
N_PUBLICATIONS   NUMBER,
IS_ESTIMATE    VARCHAR2(1));