@startuml

title __WITHABSTRACTFACTORY's Class Diagram__\n

  namespace theory.creational.abstractFactory.withAbstractFactory {
    interface theory.creational.abstractFactory.withAbstractFactory.BackGround {
        {abstract} + getBackGroundColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    interface theory.creational.abstractFactory.withAbstractFactory.Button {
        {abstract} + getButtonColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    class theory.creational.abstractFactory.withAbstractFactory.DarkBackGround {
        + getBackGroundColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    class theory.creational.abstractFactory.withAbstractFactory.DarkButton {
        + getButtonColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    class theory.creational.abstractFactory.withAbstractFactory.DarkTheme {
        + getBackGround()
        + getButton()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    class theory.creational.abstractFactory.withAbstractFactory.Main {
        {static} + main()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    interface theory.creational.abstractFactory.withAbstractFactory.Theme {
        {abstract} + getBackGround()
        {abstract} + getButton()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    class theory.creational.abstractFactory.withAbstractFactory.WhiteBackGround {
        + getBackGroundColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    class theory.creational.abstractFactory.withAbstractFactory.WhiteButton {
        + getButtonColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withAbstractFactory {
    class theory.creational.abstractFactory.withAbstractFactory.WhiteTheme {
        + getBackGround()
        + getButton()
    }
  }
  

  theory.creational.abstractFactory.withAbstractFactory.DarkBackGround .up.|> theory.creational.abstractFactory.withAbstractFactory.BackGround
  theory.creational.abstractFactory.withAbstractFactory.DarkButton .up.|> theory.creational.abstractFactory.withAbstractFactory.Button
  theory.creational.abstractFactory.withAbstractFactory.DarkTheme .up.|> theory.creational.abstractFactory.withAbstractFactory.Theme
  theory.creational.abstractFactory.withAbstractFactory.WhiteBackGround .up.|> theory.creational.abstractFactory.withAbstractFactory.BackGround
  theory.creational.abstractFactory.withAbstractFactory.WhiteButton .up.|> theory.creational.abstractFactory.withAbstractFactory.Button
  theory.creational.abstractFactory.withAbstractFactory.WhiteTheme .up.|> theory.creational.abstractFactory.withAbstractFactory.Theme


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
