@startuml

title __WITHOUTABSTRACTFACTORY's Class Diagram__\n

  namespace theory.creational.abstractFactory.withoutAbstractFactory {
    interface theory.creational.abstractFactory.withoutAbstractFactory.BackGround {
        {abstract} + getBackGroundColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withoutAbstractFactory {
    interface theory.creational.abstractFactory.withoutAbstractFactory.Button {
        {abstract} + getButtonColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withoutAbstractFactory {
    class theory.creational.abstractFactory.withoutAbstractFactory.DarkBackGround {
        + getBackGroundColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withoutAbstractFactory {
    class theory.creational.abstractFactory.withoutAbstractFactory.DarkButton {
        + getButtonColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withoutAbstractFactory {
    class theory.creational.abstractFactory.withoutAbstractFactory.Main {
        {static} + main()
    }
  }
  

  namespace theory.creational.abstractFactory.withoutAbstractFactory {
    class theory.creational.abstractFactory.withoutAbstractFactory.WhiteBackGround {
        + getBackGroundColor()
    }
  }
  

  namespace theory.creational.abstractFactory.withoutAbstractFactory {
    class theory.creational.abstractFactory.withoutAbstractFactory.WhiteButton {
        + getButtonColor()
    }
  }
  

  theory.creational.abstractFactory.withoutAbstractFactory.DarkBackGround .up.|> theory.creational.abstractFactory.withoutAbstractFactory.BackGround
  theory.creational.abstractFactory.withoutAbstractFactory.DarkButton .up.|> theory.creational.abstractFactory.withoutAbstractFactory.Button
  theory.creational.abstractFactory.withoutAbstractFactory.WhiteBackGround .up.|> theory.creational.abstractFactory.withoutAbstractFactory.BackGround
  theory.creational.abstractFactory.withoutAbstractFactory.WhiteButton .up.|> theory.creational.abstractFactory.withoutAbstractFactory.Button


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
