@startuml

title __WITHITERATOR's Class Diagram__\n

  namespace theory.behaviour.iterator.withIterator {
    interface theory.behaviour.iterator.withIterator.Iterator {
        {abstract} + hasNext()
        {abstract} + next()
    }
  }
  

  namespace theory.behaviour.iterator.withIterator {
    interface theory.behaviour.iterator.withIterator.List {
        {abstract} + theory.behaviour.iterator()
    }
  }
  

  namespace theory.behaviour.iterator.withIterator {
    class theory.behaviour.iterator.withIterator.Main {
        {static} + main()
    }
  }
  

  namespace theory.behaviour.iterator.withIterator {
    class theory.behaviour.iterator.withIterator.TopicIdIterator {
        - lastIndex : int
        - topicIds : int[]
        + TopicIdIterator()
        + hasNext()
        + next()
    }
  }
  

  namespace theory.behaviour.iterator.withIterator {
    class theory.behaviour.iterator.withIterator.TopicIdList {
        - topicIds : int[]
        + TopicIdList()
        + getTopicIds()
        + theory.behaviour.iterator()
        + setTopicIds()
    }
  }
  

  namespace theory.behaviour.iterator.withIterator {
    class theory.behaviour.iterator.withIterator.TopicNameIterator {
        - lastIndex : int
        - topicNames : String[]
        + TopicNameIterator()
        + hasNext()
        + next()
    }
  }
  

  namespace theory.behaviour.iterator.withIterator {
    class theory.behaviour.iterator.withIterator.TopicNameList {
        - topicNames : String[]
        + TopicNameList()
        + getTopicNames()
        + theory.behaviour.iterator()
        + setTopicNames()
    }
  }
  

  theory.behaviour.iterator.withIterator.TopicIdIterator .up.|> theory.behaviour.iterator.withIterator.Iterator
  theory.behaviour.iterator.withIterator.TopicIdList .up.|> theory.behaviour.iterator.withIterator.List
  theory.behaviour.iterator.withIterator.TopicNameIterator .up.|> theory.behaviour.iterator.withIterator.Iterator
  theory.behaviour.iterator.withIterator.TopicNameList .up.|> theory.behaviour.iterator.withIterator.List


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
